"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.reactionNotFoundError = exports.notReactionOwnerError = exports.notCommentAuthorError = exports.commentNotFoundError = exports.notAuthorizedError = exports.userNotFoundError = exports.userExistError = void 0;
var UserExistsError_1 = require("./userE/UserExistsError");
Object.defineProperty(exports, "userExistError", { enumerable: true, get: function () { return __importDefault(UserExistsError_1).default; } });
var UserNotFoundError_1 = require("./userE/UserNotFoundError");
Object.defineProperty(exports, "userNotFoundError", { enumerable: true, get: function () { return __importDefault(UserNotFoundError_1).default; } });
var NotAuthorizedError_1 = require("./userE/NotAuthorizedError");
Object.defineProperty(exports, "notAuthorizedError", { enumerable: true, get: function () { return __importDefault(NotAuthorizedError_1).default; } });
var CommentNotFoundError_1 = require("./commentE/CommentNotFoundError");
Object.defineProperty(exports, "commentNotFoundError", { enumerable: true, get: function () { return __importDefault(CommentNotFoundError_1).default; } });
var NotCommentAuthorError_1 = require("./commentE/NotCommentAuthorError");
Object.defineProperty(exports, "notCommentAuthorError", { enumerable: true, get: function () { return __importDefault(NotCommentAuthorError_1).default; } });
var NotReactionOwnerError_1 = require("./commentE/NotReactionOwnerError");
Object.defineProperty(exports, "notReactionOwnerError", { enumerable: true, get: function () { return __importDefault(NotReactionOwnerError_1).default; } });
var ReactionNotFoundError_1 = require("./commentE/ReactionNotFoundError");
Object.defineProperty(exports, "reactionNotFoundError", { enumerable: true, get: function () { return __importDefault(ReactionNotFoundError_1).default; } });
